### ISSUE TITLE
libvlc_new returns NULL with VLC 2.2.1

### ISSUE THREAD

**Issue by robertoostenveld** [durka/vlc-matlab#1]
Hi Alex,

Thanks for sharing vlc-matlab, which looks like a very promising possibility for playing video in MATLAB. I ran into a problem and hope you might be able to help.

I am working on OS X 10.9.5 with MATLAB R2014b and can compile with the "build_mac.sh" script without problem. However, when I do

vlc_setup
vh = vlc_wrapper('init')
Warning: VLC instance is NULL 
vh =
     0

and then try to open an avi file with 
vp = vlc_wrapper('open', vh, 'movie.avi')

MATLAB crashes with a segmentation violation in the mex file. I suppose this is due to the NULL instance, which I traced back to line 107 in vcl.cpp, where apparently libvlc_new returns NULL. That is where I get stuck. 

All dynamically linked libraries seem to be in place:

mac011> otool -L vlc.mexmaci64 
vlc.mexmaci64:
    /Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib (compatibility version 11.0.0, current version 11.0.0)
    /Users/roboos/matlab/vlc-matlab/osx/MexWindowHelper/build/Release/libMexWindowHelper.dylib (compatibility version 1.0.0, current version 1.0.0)
    @rpath/libmx.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libmex.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libmat.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 60.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

Do you have an idea what might be wrong?

thanks,
Robert

**Comment by durka** [comment]
This is certainly a problem. Sorry for the slow reply. I am using the same versions of Mac OSX and Matlab, so hopefully I can diagnose the problem.

First can I ask, what version of vlc-matlab are you using? Have you checked out the git HEAD, or are you using the tagged 0.2.0 release?

**Comment by durka** [comment]
I do see two small differences in your `otool -L` output versus mine:
- your binary is linked to libstdc++ as opposed to libc++
- you have a slightly newer version of libvlc.dylib

For further diagnostics, would you mind running the following Matlab commands:

``` matlab
>> cc = mex.getCompilerConfigurations('c++')
>> save cc.mat cc
```

... and send me the resulting file.

**Comment by robertoostenveld** [comment]
Hi Alex,

I am using HEAD (and should admit that I did not consider that there might be a more stable tagged version).

```
>> cc = mex.getCompilerConfigurations('c++')

cc = 

  CompilerConfiguration with properties:

             Name: 'Clang++'
     Manufacturer: 'Apple'
         Language: 'C++'
          Version: ''
         Location: ''
        ShortName: 'mex'
         Priority: 'A'
          Details: [1x1 mex.CompilerConfigurationDetails]
       LinkerName: ''
    LinkerVersion: ''
           MexOpt: '/Users/roboos/.matlab/R2014b/mexopts.sh'

```

The file is available from https://dl.dropboxusercontent.com/u/3206396/cc.mat

**Comment by durka** [comment]
Well, this is quite strange. I tried changing libstdc++ vs. libc++ and that doesn't seem to be an issue here. My mex setup is different from yours because I have XCode installed so it compiles through that. So that may be something to try. Also checking the exact version of VLC -- I have 2.1.5.

**Comment by robertoostenveld** [comment]
could I try your (compiled) mex file?

**Comment by robertoostenveld** [comment]
oh, I have VLC 2.2.1

**Comment by durka** [comment]
Ah, that's the problem I believe! I do remember some trouble when I tried to upgrade VLC. Should have put it in the README. I do want to fix this, but for now please try version 2.1.5; you can get it [here](http://download.videolan.org/pub/videolan/vlc/2.1.5/macosx/). And my compiled binary is [here](http://alexburka.com/tmp/vlc.mexmaci64) though I doubt it will work for you due to various system differences.

**Comment by robertoostenveld** [comment]
removing 2.2.1, installing 2.1.5 and recompiling solved it. Thanks!

**Comment by durka** [comment]
Thanks, I added a note to the README for now.

**Comment by durka** [comment]
I added a workaround and I think it works with VLC 2.2.1 now, if you're interested to try.
